name: CI

on:
  push:

  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'tess-git'
          
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: tess-git
          pkgbuild: tess-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
